// src/styles.ts (Fuera de src/app/)
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#000' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#000',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  headerLeft: { flexDirection: 'row', alignItems: 'center' },
  headerAvatar: { width: 38, height: 38, borderRadius: 19, marginRight: 10 },
  headerTextContainer: { justifyContent: 'center' },
  headerTitle: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
  headerStatus: { color: '#00FF7F', fontSize: 11 },
  headerActions: { flexDirection: 'row', alignItems: 'center' },
  actionIcon: { marginLeft: 16, padding: 4 },
  chatContainer: { flex: 1 },
  listContent: { paddingHorizontal: 16, paddingVertical: 20 },
  dateContainer: { alignItems: 'center', marginVertical: 12 },
  dateText: {
    color: 'rgba(255, 255, 255, 0.6)',
    fontSize: 12,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
  },
  messageRow: { flexDirection: 'row', marginVertical: 6, alignItems: 'flex-end' },
  userRow: { justifyContent: 'flex-end' },
  kimyRow: { justifyContent: 'flex-start' },
  chatAvatarRow: { width: 28, height: 28, borderRadius: 14, marginHorizontal: 6 },
  rowPlaceholder: { backgroundColor: '#333', justifyContent: 'center', alignItems: 'center' },
  bubble: { maxWidth: '75%', padding: 12, borderRadius: 16 },
  userBubble: { backgroundColor: '#FF1493', borderBottomRightRadius: 4 },
  kimyBubble: {
    backgroundColor: 'rgba(20, 20, 30, 0.85)',
    borderBottomLeftRadius: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
  },
  usernameTag: { color: '#FFE4E1', fontSize: 11, fontWeight: 'bold', marginBottom: 2 },
  messageText: { color: '#fff', fontSize: 15, lineHeight: 20 },
  timeText: { color: 'rgba(255, 255, 255, 0.5)', fontSize: 10, marginTop: 4, alignSelf: 'flex-end' },
  typingContainer: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 8, backgroundColor: 'rgba(0,0,0,0.4)' },
  typingText: { color: 'rgba(255,255,255,0.7)', fontSize: 12, marginLeft: 8 },
  footer: { padding: 10, backgroundColor: 'rgba(0,0,0,0.6)' },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 24,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  input: { flex: 1, color: '#fff', fontSize: 15, maxHeight: 100, paddingTop: 6, paddingBottom: 6 },
  sendButton: {
    backgroundColor: '#FF1493',
    borderRadius: 20,
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
  },
  backButton: { padding: 4 },
  settingsContent: { flex: 1, padding: 24, backgroundColor: '#000' },
  avatarContainerSettings: { alignSelf: 'center', marginBottom: 30 },
  settingsAvatarPreview: { width: 110, height: 110, borderRadius: 55, borderWidth: 2, borderColor: '#FF1493' },
  avatarPlaceholderSettings: { backgroundColor: '#1a1a1a', justifyContent: 'center', alignItems: 'center' },
  placeholderTextSettings: { color: '#fff', fontSize: 12, marginTop: 4 },
  label: { color: '#fff', fontSize: 14, marginBottom: 8, fontWeight: '600' },
  settingsInput: {
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    color: '#fff',
    fontSize: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    marginBottom: 24,
  },
  saveButton: { backgroundColor: '#FF1493', borderRadius: 12, paddingVertical: 14, alignItems: 'center' },
  saveButtonText: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
  alertOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'center', alignItems: 'center' },
  alertBox: { width: '80%', backgroundColor: '#111', borderRadius: 16, padding: 20, borderStyle: 'solid', borderWidth: 1, borderColor: '#FF1493' },
  alertTitle: { color: '#fff', fontSize: 18, fontWeight: 'bold', marginBottom: 8, textAlign: 'center' },
  alertMessage: { color: 'rgba(255,255,255,0.8)', fontSize: 14, textAlign: 'center', marginBottom: 20, lineHeight: 20 },
  alertButtonsContainer: { flexDirection: 'row', justifyContent: 'space-around' },
  alertButton: { flex: 1, paddingVertical: 10, backgroundColor: '#FF1493', borderRadius: 8, marginHorizontal: 5, alignItems: 'center' },
  alertBtnDestructive: { backgroundColor: '#D32F2F' },
  alertButtonText: { color: '#fff', fontWeight: 'bold', fontSize: 14 },
  alertBtnCancelText: { color: '#fff' },
  toastContainer: {
    position: 'absolute',
    top: 90,
    alignSelf: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FF1493',
    zIndex: 999,
  },
  toastText: { color: '#fff', fontSize: 13, fontWeight: '500' }
});